# Docker Compose configuration file
#
# References:
#
# * Compose Specification | Compose file reference | Reference | Docker Docs
#   https://docs.docker.com/compose/compose-file/
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0
name: gruntjs-com
services:
  # Environment for developing the project
  dev-environment:
    container_name: gruntjs-com-dev
    hostname: gruntjs-com-dev
    image: ubuntu:24.04
    volumes:
      - type: bind
        source: ./
        target: /project
    environment:
      # Avoid debconf prompts at all costs
      - DEBIAN_FRONTEND=noninteractive
    init: true
    command: sleep infinity
    profiles:
      - dev
    ports:
      - 127.0.0.1:5678:5678
